### ISSUE TITLE
Impossible to sroll on the mobile version

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#542]
When there are several accounts it is impossible to validate the form.

**Comment by nicofrand** [comment]
Needs some further tests but this should fix it:

```CSS
.container {
    height: 100%;
    overflow: auto;
}
```
